name: Docker Image deployment to azure web app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: 'github-action-docker-demo'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{env.DOCKER_IMAGE_NAME}}:latest
    
    -name: Azure login
    uses: azure/login@v1
    with:
       creds: gi${{secret.AZUREAPPSERVICE_PUBLISHPROFILE_1B8726602DBB478893C39476697CF77D}}